homework-7
Artur-Sgi/MK-JSMarathon pull request #6
Opened 2021-12-20 19:49 UTC by Artur-Sgi

2021-12-21 21:02 UTC, ZarMarathon commented on services/FightService.js
> +const createPlayer = (playerObj) => {
Если передаешь в стрелочную функцию один аргумент, то можно записывать без скобок

2021-12-21 21:07 UTC, ZarMarathon requested changes
А main.js куда делся-то?)) Пока апрув не поставлю, доделай, пожалуйста)

2021-12-21 21:23 UTC, Artur-Sgi commented
> А main.js куда делся-то?)) Пока апрув не поставлю, доделай, пожалуйста)
main.js поправлен в предыдущем ПРе https://github.com/Artur-Sgi/MK-JSMarathon/pull/5/

2021-12-21 21:27 UTC, Artur-Sgi commented on services/FightService.js
> +const createPlayer = (playerObj) => {
Угу, поправил настройки в `.prettierrc`

2021-12-23 06:54 UTC, ZarMarathon approved these changes
Убедил, апрув)

2021-12-23 07:07 UTC, merged